apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
      auth:
        # reference to a Kubernetes Secret that contains AWS credentials
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: aws-creds
            key: AWS_SECRET_ACCESS_KEY
