apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-webhook
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets  
  target:
    name: slack-webhook
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: slack/webhook  
        property: url       
