- name: Deploy ArgoCD on EKS
  hosts: local
  tasks:
    - name: Create namespace for ArgoCD
      command: kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -

    - name: Install ArgoCD using manifests
      command: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

    - name: Wait for ArgoCD server rollout
      command: kubectl -n argocd rollout status deploy/argocd-server

    - name: Apply Ingress for ArgoCD
      copy:
        dest: /tmp/argocd-ingress.yaml
        content: |
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: argocd-server-ingress
            namespace: argocd
            annotations:
              kubernetes.io/ingress.class: alb
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
          spec:
            rules:
              - host: myprofile.com
                http:
                  paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: argocd-server
                        port:
                          number: 443
      register: ingress_file

    - name: Apply ingress file
      command: kubectl apply -f /tmp/argocd-ingress.yaml
