name: App-CI-CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: eks-cluster

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Maven Test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:check || echo "Checkstyle skipped"

      - name: Setup Sonar Scanner
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarCloud Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=src \
            -Dsonar.java.binaries=target/classes

  Build_And_Publish:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Build & Push APP Image
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.ECR_REGISTRY }}
          repo: ${{ secrets.ECR_REGISTRY }}/app
          region: ${{ env.AWS_REGION }}
          tags: latest
          dockerfile: ./Docker-app/Dockerfile
          context: .

      - name: Build & Push DB Image
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.ECR_REGISTRY }}
          repo: ${{ secrets.ECR_REGISTRY }}/db
          region: ${{ env.AWS_REGION }}
          tags: latest
          dockerfile: ./Docker-db/Dockerfile
          context: ./Docker-db  

      - name: Build & Push WEB Image
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.ECR_REGISTRY }}
          repo: ${{ secrets.ECR_REGISTRY }}/web
          region: ${{ env.AWS_REGION }}
          tags: latest
          dockerfile: ./Docker-web/Dockerfile
          context: ./Docker-web

  Deploy:
    runs-on: ubuntu-latest
    needs: Build_And_Publish
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory ansible/playbook.yml

      - name: Install Helm
        run: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod +x get_helm.sh && ./get_helm.sh

      - name: Deploy Monitoring
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
          helm upgrade --install kube-prom prometheus-community/kube-prometheus-stack -n monitoring --create-namespace

      - name: Deploy ArgoCD
        run: |
          kubectl create namespace argocd || true
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          kubectl rollout status deployment argocd-server -n argocd

      - name: Apply ArgoCD App CR
        run: kubectl apply -f argocd/argocd-app.yaml -n argocd
